### ISSUE TITLE
Question About Answer

### ISSUE THREAD

**Issue by JoeZiminski** [fifthist/Introduction-To-Probability-Blitzstein-Solutions#20]
Hi fifthist,

[Apologies I accidently posted this question separately on a work account, if you could kindly delete the other post I will remove this tag]

Thanks again for this great resource, I am working through the book and would have given up if not for having access to these answers.

I have a question about an identity used in your answer to question 41 (Conditional Probability, Monday Hall). The conditional probability P(A , B | C) becomes P(A | B, C) P(B, C). Did you find this in the book (I could not see it) or elsewhere / figure it out yourself? I am struggling a little with how to manipulate / solve these problems requiring extra-conditioning.

Many Thanks,
Joe

**Comment by fifthist** [comment]
Hi Joe,

Glad you are finding the resource useful.
Regarding your question, P(A,B|C) is not equal P(A|B,C)P(B,C), but it is equal to P(A|B,C)P(B|C).

Image the conditioning isn't there. You'd have P(A,B) = P(B)P(A|B). As the book says, conditional probabilities are just probabilities themselves, and they adhere to all the rules of non-conditional probabilities. By conditioning on C, you are creating a new probability space, where probabilities are computed with P(*|C). Again, since all the regular probability rules apply, we apply the equation above in the context of this new probability space *|C and we get P(A,B|C) = P(B|C)P(A|B,C).

Hope that is helpful.

**Comment by JoeZiminski** [comment]
Thanks, this was very helpful!
